version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - yarn --frozen-lockfile --non-interactive
  build:
    commands:
      - VERSION=$(node -e "console.log(require('./package.json').version)")
      - yarn lint
      - yarn test
      - yarn build
      - yarn docs
      - npm config set '//registry.npmjs.org/:_authToken' $(aws ssm get-parameter --name npm-publish-token --with-decryption --query Parameter.Value)
      - npm publish --access public
      - aws s3 rm --recursive s3://dragonchain-sdk-node-docs/latest/*
      - aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/latest
      - aws s3 rm --recursive s3://dragonchain-sdk-node-docs/$VERSION/*
      - aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/$VERSION/
      - aws s3api put-object --website-redirect-location /latest --content-type text/html --bucket dragonchain-sdk-node-docs --key index.html
