Description: CI/CD Pipeline for DragonchainSdkNode

Parameters:
  GitHubSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: GitHubReadOnlyToken
  IntegrationTestApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DragonchainNodeSdkIntegrationTestApiKey

Resources:
  UnittestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: 'dragonchain-sdk-node-unittest-codebuild-project'
      ServiceRole:
        Ref: TestingCodebuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/nodejs:8.11.0
        EnvironmentVariables:
          - Name: STAGE
            Type: PLAINTEXT
            Value: stage
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.unittest.yml
      TimeoutInMinutes: 10

  IntegrationCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: 'dragonchain-sdk-node-integration'
      ServiceRole:
        Ref: TestingCodebuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/nodejs:8.11.0
        EnvironmentVariables:
          - Name: STAGE
            Type: PLAINTEXT
            Value: stage
          - Name: API_KEY
            Type: PLAINTEXT
            Value:
              Ref: IntegrationTestApiKey
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.integration.yml
      TimeoutInMinutes: 10

  ProdDeployCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: 'dragonchain-sdk-node-deploy-prod'
      ServiceRole:
        Ref: ProdCodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/nodejs:8.11.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.deploy.yml
      TimeoutInMinutes: 10

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dragonchain-sdk-node-CodePipelineRole
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com, codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'sts:AssumeRole'
                - 'codebuild:*'
                - 's3:*'
                Effect: Allow
                Resource: '*'

  ProdCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dragonchain-sdk-node-ProdCodebuildRole
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com,  codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyName: ProdNodeSdkCodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 's3:*'
                Effect: Allow
                Resource: '*'
              # NPM_PUBLISH_TOKEN PERMISSIONS
              - Action:
                - 'ssm:GetParameter'
                Effect: Allow
                Resource: arn:aws:ssm:us-west-2:381978683274:parameter/npm-publish-token
              - Action:
                - 'kms:Decrypt'
                Effect: Allow
                Resource: arn:aws:kms:us-west-2:381978683274:key/277b0ec3-8c59-4647-8909-183db0226586

  TestingCodebuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dragonchain-sdk-node-TestingCodebuildRole
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com,  codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyName: TestingCodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                Effect: Allow
                Resource: '*'
              - Action:
                - 's3:*'
                Effect: Allow
                Resource: 'arn:aws:s3:::dragonchain-sdk-node-codebuild-artifacts/*'
              - Action:
                - 'secretsmanager:GetSecretValue'
                Effect: Allow
                Resource: 'arn:aws:secretsmanager:us-west-2:381978683274:secret:dragonchain-sdk-integration-key-?????'

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dragonchain-sdk-node-codebuild-artifacts

  DocsWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dragonchain-sdk-node-docs
      WebsiteConfiguration:
        IndexDocument: index.html

  ReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DocsWebsiteBucket
      PolicyDocument:
        Statement:
        - Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub 'arn:aws:s3:::${DocsWebsiteBucket}/*'
          Principal: '*'


  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DragonchainSdkNodeCodePipeline
      ArtifactStore:
        Location:
          Ref: ArtifactBucket
        Type: S3
      RestartExecutionOnUpdate: true
      RoleArn:
        Fn::GetAtt: CodePipelineRole.Arn
      Stages:
        - Name: Github
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: dragonchain-inc
                Repo: dragonchain-sdk-node
                Branch: master
                OAuthToken:
                  Ref: GitHubSecret
              OutputArtifacts:
                - Name: DragonchainSdkNode
              RunOrder: 1
        - Name: Test
          Actions:
            - Name: Unit
              ActionTypeId:
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:
                  Ref: UnittestCodeBuildProject
              InputArtifacts:
                - Name: DragonchainSdkNode
              OutputArtifacts:
                - Name: BuiltDragonchainSdkNode
              RoleArn:
                Fn::GetAtt: CodePipelineRole.Arn
              RunOrder: 2
            - Name: Integration
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:
                  Ref: IntegrationCodeBuildProject
              InputArtifacts:
                - Name: DragonchainSdkNode
              OutputArtifacts:
                - Name: TestedDragonchainSdkNode
              RoleArn:
                Fn::GetAtt: CodePipelineRole.Arn
              RunOrder: 2
        - Name: Prod
          Actions:
          - Name: Test-Build-Deploy
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            Configuration:
              ProjectName:
                Ref: ProdDeployCodeBuildProject
            InputArtifacts:
              - Name: DragonchainSdkNode
            OutputArtifacts:
              - Name: BuiltDragonchainSdkNodeProdCode
            RoleArn:
              Fn::GetAtt: CodePipelineRole.Arn
            RunOrder: 5
